### ISSUE TITLE
Signature issue

### ISSUE THREAD

**Issue by szepeviktor** [autonome/Always-Right#1]
Good afternoon!

I install your extension by coping it to core\browser\extensions.
```js
// Activate extensions in core
user_pref("extensions.autoDisableScopes", 11); // 15 - 4 = ALL - SCOPE_APPLICATION
user_pref("extensions.enabledScopes", 5); // 15 - 8 - 2 = ALL - SCOPE_SYSTEM - SCOPE_USER
```

And there is this error in Developer Edition v45
![ar](https://cloud.githubusercontent.com/assets/952007/12373335/65381c4a-bc76-11e5-8e60-90fd4ac3d182.jpg)

Could you advise?

**Comment by szepeviktor** [comment]
@autonome May mentioning you helps.

**Comment by szepeviktor** [comment]
Setting `xpinstall.signatures.required` to false is a work-around.

**Comment by autonome** [comment]
Hello!

Yes, setting that pref is a workaround.

The proper way is to install from
https://addons.mozilla.org/en-us/firefox/addon/always-right/

**Comment by szepeviktor** [comment]
I hope I get an answer
https://support.mozilla.org/en-US/questions/1105073

**Comment by szepeviktor** [comment]
@autonome Actually I am using Firefox in a  extract-run-delete way, so addons have to be preinstalled (I do not have time to install and set everything every day).

**Comment by autonome** [comment]
I don't know extract-run-delete... can you explain?

**Comment by szepeviktor** [comment]
It is very simple: I download setup.exe, extract core/* from it, run firefox.exe, and when closing Firefox I delete everything even the profile. Actually it runs from a ramdisk.

**Comment by szepeviktor** [comment]
We've got an answer!!

> I checked the signedState in the extensions.json file and notice 
signedState: 1
> This means SIGNEDSTATE_PRELIMINARY: 1 - Add-on is preliminarily reviewed That might be the cause that the extension only works when installed in the profile folder. Other extensions that work may have:SIGNEDSTATE_SIGNED: 2 - Add-on is fully reviewed

**Comment by szepeviktor** [comment]
@autonome Could get Always Right *fully reviewed*? How could I help?
https://support.mozilla.org/hu/questions/1105073

**Comment by autonome** [comment]
Sure, I'll submit it for review.

**Comment by autonome** [comment]
Done. It's fully reviewed now.

**Comment by szepeviktor** [comment]
Thank you very much.

**Comment by szepeviktor** [comment]
@autonome Could you upload it as a new release?

**Comment by szepeviktor** [comment]
Excuse me 1.5.0 was already released.
