### ISSUE TITLE
Weird tab behavior in web extention

### ISSUE THREAD

**Issue by dingdingdon** [autonome/Always-Right#12]
I used to use open-tabs-next-to-current add on, but it broke since migrating to web extension, I already report that issue in the link below. Your add on has the same issue after the new update to web extension. Do you have any solution to fix this? 

https://github.com/sblask/webextension-open-tabs-next-to-current/issues/32#issuecomment-317111763

**Comment by yfdyh000** [comment]
"Open Tabs Next To Current" work for me always, maybe your Firefox or profile has weird configuration.

**Comment by dingdingdon** [comment]
The profile is refreshed profile, most of the time work but fail when I use it with iMacro because it runs a lot faster than human does, I have 6 profiles and 4 version of Firefox from ESR to Night for work to test on my computer. Did you follow the steps that I provided in the link above to duplicate the issue?

**Comment by autonome** [comment]
Hi, I'm sorry but I don't know what imacro is, and don't have time to learn
what another extension is doing, let alone two different other extensions.

This extension is *very* simple, as you can see from the very small amount
of source code. There's really not any other way of doing what I'm doing in
this add-on.

If you're seeing this problem with other extensions doing the same exact
thing, then it's either a problem with the WebExtension implementation in
Firefox, or a problem with imacro.

**Comment by autonome** [comment]
Closing. Can't fix without a reduced testcase or more information, sorry :(
