### ISSUE TITLE
New tabs from the same domain name don't always open to the right

### ISSUE THREAD

**Issue by smartfonreddit** [autonome/Always-Right#17]
Hello. Let's say there are 10 tabs with the same domain name (e.g. AndroidPolice dot com). The 4th tab from the left is on foreground. I find a link on that page, that's also from AndroidPolice, right click and open it in new tab. It doesn't always open next to the 4th tab. It's not easy to reproduce. It started happening few days ago. I'm using Windows 10, Firefox 57 Beta 64bit. 
Could it be related to a change that was done to Firefox to fix this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1402205

**Comment by smartfonreddit** [comment]
FYI the problem was happening only in Private window mode, which is expected, I suppose.

**Comment by autonome** [comment]
Hrm, I thought I responded to this, sorry!

I usually don't spend time in PB other than single-tab-and-close-window
type of usage. Does the add-on not work at all there?

**Comment by autonome** [comment]
Hm, I tested and cannot reproduce this behavior. I also asked about PB in
#webextensions on Mozilla IRC and there should not be a problem with this
running in private browsing mode.

I don't know how to fix if I cannot reproduce 😭
