### ISSUE TITLE
2.0.6 stopped working for me in Nightly 58.0a1 (2017-10-19)

### ISSUE THREAD

**Issue by kumar303** [autonome/Always-Right#18]
Does it work for you? I updated today to 58.0a1 (2017-10-19) and tabs no longer open to the right at all. I haven't updated in several days so I'm not sure when it broke.

**Comment by autonome** [comment]
i tested on nightly latest build on Mac and works fine. which OS are you on?

**Comment by kumar303** [comment]
Ah, cool, it seems to have fixed itself as of 2017-10-20. All good now on today's Nightly too. I am on Mac 10.12.6
