### ISSUE TITLE
Last Tab Moves To Position Two On Browser Restart

### ISSUE THREAD

**Issue by MagicSquaresMark** [autonome/Always-Right#19]
When I close Firefox, what was the last tab on the right moves to the second tab from the left when I re-open the browser.

I'm currently running version 56.0.2 (64-bit), but it was also happening with the previous version 56.0.1.

Any way to stop this from happening?

Thanks!

**Comment by autonome** [comment]
Thanks for reporting! Which OS?

How many tabs do you have open?

**Comment by MagicSquaresMark** [comment]
Windows 7 Professional.

About 24 tabs at the moment.

**Comment by tummychow** [comment]
Can also reproduce this on Arch Linux, FF 57.0, with anywhere from 3 to 10 tabs restored at startup.

**Comment by autonome** [comment]
This should be fixed with Firefox 61 now that #22 is landed, which uses the official built-in support for tab placement.
