### ISSUE TITLE
Not always right - see example in description below

### ISSUE THREAD

**Issue by git511** [autonome/Always-Right#23]
Start from a web page ('Tab0') with several links on it. Open one of these links in a new tab ('Tab1') (in background, so focus stays on initial page). Then do same with another link on Tab0: the new tab, Tab2, opens to the right of Tab1, not of Tab0.

Behaviour continues if I open another link in background, it opens in Tab 3 to the right of Tab2, etc.

The behaviour I am looking for is that the last opened tab is indeed directly to the right of Tab0 (preferences might differ depending on user, so maybe that could be a user-configurable setting).

Instead it is as if the last created tab is considered as the active tab to the right of which the next opened tab should be placed, even though I am still on Tab0.

I use an add-on, Right Links WE, to open tabs from a link while staying on the page/tab on which that link is. I cannot say to what extent the behaviour results from this addon, I have not tried getting the same functionality by other means (e.g. modifying some about:config preferences).

Thanks if you have a chance to look into it.

**Comment by autonome** [comment]
Thanks for filing!

While this is issue *#23*... filed on Oct *23* (my birthday)... I've already discussed this in #24, so going to close this item in favor of that one, and keep this one as a special keepsake.
