### ISSUE TITLE
Not functional in Nightly 53.0a1?

### ISSUE THREAD

**Issue by blissdev** [autonome/Always-Right#5]
I've had great experiences in the past with this plugin (while also running Nightly), but recently it seems to have stopped working. Tabs just open to the far right in all cases. Has anyone else seen this behavior?

Firefox: 53.0a1 (2016-12-14) (64-bit)
OS: macOS 10.12.2 (16C67)

**Comment by autonome** [comment]
Yep, and a fix was submitted. I'll update on AMO tonight!

**Comment by blissdev** [comment]
@autonome sweet deal!

**Comment by autonome** [comment]
Just pushed to AMO, waiting on approval.

**Comment by blissdev** [comment]
Updated and working great. Thanks!
