### ISSUE TITLE
Always Right is not a multi-process compatible extension

### ISSUE THREAD

**Issue by cpeterso** [autonome/Always-Right#6]
Firefox will soon only support multi-process compatible extensions and Always Right is not one. To test, set the `extensions.allow-non-mpc-extensions` pref to false. The Add-ons Manager will disable the extension and show the warning: "alwaysright has been disabled since it is not multiprocess compatible."

For more information about this warning, see https://wiki.mozilla.org/Add-ons/ShimsNightly.

**Comment by blissdev** [comment]
Do we know what it would take to multiprocess compatible? I'm not sure how deep of a change it is, would it require essentially starting from scratch?

**Comment by autonome** [comment]
Yeah it's basically starting from scratch. I ported to WebExtension a while
back. This add-on is quite simple, so it's only a few lines of code.
However, I experienced weird issues. I'll try to have another look.

**Comment by autonome** [comment]
Oh the code is in this branch:
https://github.com/autonome/Always-Right/tree/webextension

**Comment by blissdev** [comment]
@autonome What weird issues did you experience?

**Comment by autonome** [comment]
I can't remember exactly offhand. Will try again soon.

**Comment by autonome** [comment]
Tested against release Firefox, seemed to work ok, so bundled and submitted
for review.

https://addons.mozilla.org/en-US/developers/addon/always-right/versions/2094103

**Comment by autonome** [comment]
Pushed to AMO a few days ago, so closing this.

No victory though... the WebExtension is broken in a bunch of ways. I recommend reverting to the older version for now.
