### ISSUE TITLE
Always Right opens new tab in wrong position after current tab is dragged to new position

### ISSUE THREAD

**Issue by cpeterso** [autonome/Always-Right#9]
STR:
1. Open a new window.
2. Open three new tabs.
3. Select tab 1.
4. Drag tab 1 to replace tab 3 position.
5. Press Ctrl+T to open a new tab.

EXPECTED RESULT
The new tab should appear to the right of tab 3.

ACTUAL RESULT:
The new tab appears to the right of tab 1 because that was the old position of tab 3 before it was dragged. Always Right seems to only check the current tab position when the tab is selected, not when the new tab is opened.

I am using Always Right add-on version 1.6.1.

**Comment by autonome** [comment]
Hrm, yeah looks like I'm caching the index of the last active tab. It only
changes when the active tab changes. Which means it's likely always been
broken for tab drag-and-drop. I never noticed that because I never do it!
